id: IE4ED24CB
legacy_id: P006851
ocr_import_info:
  bdrc_scan_id: W1KG25068
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T01:47:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:05:52.851001+00:00'
last_modified: 2022-08-31 22:06:05.840633
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25068
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25068
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་སྨད་ཆོས་ཐོག་ཁག་གི་ལོ་རྒྱུས།
statistics:
  ocr_word_mean_confidence_index: 0.7704881471661977
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG25070:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25070
      total_pages: 348
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25070.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7704881471661977
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
